version: "3.9"

services:
  app:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    ports: ["1337:1337"]
    volumes: ["./:/home/bun/app"]
